# Generated by Django 4.1.6 on 2023-02-08 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nominationdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominationdetails',
            old_name='electoral_post',
            new_name='aspirant_post',
        ),
    ]
