# Generated by Django 4.1.6 on 2023-02-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_nominationdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationdetails',
            name='officer_name',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
