# Generated by Django 4.1.6 on 2023-02-08 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_electoral_post_nominationdetails_aspirant_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominationdetails',
            old_name='candidate_school',
            new_name='aspirant_school',
        ),
        migrations.RenameField(
            model_name='nominationdetails',
            old_name='aspirant_post',
            new_name='electoral_post',
        ),
    ]
