# Generated by Django 4.1.6 on 2023-02-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_nominationdetails_officer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominationdetails',
            options={'ordering': ['officer_name'], 'verbose_name_plural': 'Nomination Details'},
        ),
        migrations.AddField(
            model_name='nominationdetails',
            name='approved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='nominationdetails',
            name='has_nominated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
