# Generated by Django 4.1.6 on 2023-02-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_nominationdetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominationdetails',
            name='approved',
        ),
        migrations.AddField(
            model_name='aspirants',
            name='approved',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
