# Generated by Django 4.1.6 on 2023-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_candidate_school_nominationdetails_aspirant_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationdetails',
            name='has_nominated',
            field=models.BooleanField(default=False),
        ),
    ]
