# Generated by Django 4.1.6 on 2023-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_nominationdetails_aspirant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationdetails',
            name='aspirant_name',
            field=models.CharField(max_length=100),
        ),
    ]
