# Generated by Django 4.1.2 on 2022-10-10 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(max_length=7)),
                ('phone_no', models.CharField(max_length=14)),
                ('age', models.PositiveIntegerField(default=0)),
                ('dob', models.DateField(null=True)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='VotersDps/')),
                ('school', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('registered', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('voter', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Voters',
                'ordering': ['voter'],
            },
        ),
        migrations.CreateModel(
            name='Aspirants',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('bio', models.TextField()),
                ('post', models.CharField(max_length=20)),
                ('slogan', models.CharField(blank=True, max_length=50)),
                ('pic', models.ImageField(default='default.jpg', upload_to='Aspirant-Dps/')),
                ('form', models.FileField(upload_to='Nomination-Forms/')),
                ('nominate', models.BooleanField(default=False)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('apply', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('aspirant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='voters.voters')),
            ],
            options={
                'verbose_name_plural': 'Aspirants',
                'ordering': ['aspirant'],
            },
        ),
    ]
