# Generated by Django 4.1.3 on 2022-11-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voted',
            old_name='polled',
            new_name='voted',
        ),
    ]
