# Generated by Django 4.1.2 on 2022-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirants',
            name='pic',
            field=models.ImageField(upload_to='Aspirant-Dps/'),
        ),
    ]
