# Generated by Django 4.1.3 on 2022-11-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirants',
            name='votes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
