# Generated by Django 4.1.2 on 2022-10-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspirants',
            options={'ordering': ['name'], 'verbose_name_plural': 'Aspirants'},
        ),
        migrations.RenameField(
            model_name='aspirants',
            old_name='apply',
            new_name='applied',
        ),
        migrations.RemoveField(
            model_name='aspirants',
            name='aspirant',
        ),
        migrations.AddField(
            model_name='aspirants',
            name='alias',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='aspirants',
            name='name',
            field=models.OneToOneField(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='voters.voters'),
        ),
        migrations.AddField(
            model_name='voters',
            name='reg_no',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='aspirants',
            name='pic',
            field=models.ImageField(default='default.png', upload_to='Aspirant-Dps/'),
        ),
        migrations.AlterField(
            model_name='aspirants',
            name='post',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='voters',
            name='age',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='voters',
            name='school',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='voters',
            name='semester',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='voters',
            name='year',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('written', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.aspirants')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['written'],
            },
        ),
    ]
