# Generated by Django 4.1.2 on 2022-10-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_alter_aspirants_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirants',
            name='alias',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='voters',
            name='reg_no',
            field=models.CharField(max_length=14),
        ),
    ]
