# Generated by Django 4.1.2 on 2022-10-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_alter_aspirants_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirants',
            name='name',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='voters.voters'),
        ),
        migrations.AlterField(
            model_name='voters',
            name='reg_no',
            field=models.CharField(max_length=14),
        ),
    ]
