# Generated by Django 4.1.3 on 2022-11-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_alter_aspirants_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.CharField(editable=False, max_length=18, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(editable=False, max_length=20)),
                ('academic', models.BooleanField(default=False, editable=False)),
                ('general_rep', models.BooleanField(default=False, editable=False)),
                ('ladies_rep', models.BooleanField(default=False, editable=False)),
                ('treasurer', models.BooleanField(default=False, editable=False)),
                ('governor', models.BooleanField(default=False, editable=False)),
                ('president', models.BooleanField(default=False, editable=False)),
                ('polled', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Voted',
            },
        ),
    ]
