# Generated by Django 4.1.4 on 2023-02-03 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(max_length=7)),
                ('phone_no', models.CharField(max_length=14)),
                ('age', models.PositiveIntegerField(default=0, editable=False)),
                ('dob', models.DateField(null=True)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='Voters-Dps/')),
                ('reg_no', models.CharField(max_length=14)),
                ('school', models.CharField(max_length=70)),
                ('year', models.CharField(max_length=12)),
                ('semester', models.CharField(max_length=1)),
                ('registered', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('voter', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Voters',
                'ordering': ['voter'],
            },
        ),
        migrations.CreateModel(
            name='Officials',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(max_length=7)),
                ('phone_no', models.CharField(max_length=14)),
                ('dob', models.DateField(null=True)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='Officials-Dps/')),
                ('school', models.CharField(max_length=70)),
                ('role', models.CharField(max_length=25)),
                ('is_official', models.BooleanField(default=False, editable=False)),
                ('registered', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('officer', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Electoral Officials',
                'ordering': ['officer'],
            },
        ),
    ]
