# Generated by Django 4.1.2 on 2022-10-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polled',
            fields=[
                ('id', models.CharField(editable=False, max_length=18, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(editable=False, max_length=20)),
                ('post', models.CharField(max_length=32)),
                ('polled', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Polled',
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=32)),
                ('total_polls', models.PositiveIntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='voters.aspirants')),
            ],
            options={
                'verbose_name_plural': 'Polls',
                'ordering': ['total_polls'],
            },
        ),
    ]
