# Generated by Django 4.1.2 on 2022-10-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_polled_alter_polls_edited_alter_polls_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polled',
            name='id',
            field=models.CharField(editable=False, max_length=18, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='total_polls',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
