# Generated by Django 4.1.2 on 2022-10-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_polled_id_alter_polls_total_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='polled',
            name='post',
            field=models.CharField(default='', max_length=32),
        ),
    ]
